YarnsMobile/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using YarnsMobile.Models;
using YarnsMobile.Repositories;

namespace YarnsMobile.Controllers
{
    public class BooksController : Controller
    {
        private IRepository _repository;
        private IHostingEnvironment _environment;
        public BooksController(IRepository repository, IHostingEnvironment environment)
        {
            _repository = repository;
            _environment = environment;
        }
        public IActionResult BrowseBooks()
        {
            var books = _repository.GetBooks();
            return View(books);
        }

        public IActionResult MyBooks()
        {
            return View();
        }

        [Route("Books/Details/{id}")]
        public IActionResult Details()
        {
            return View();
        }

        public IActionResult GetImage(int id)
        {
            Book requestedBook = _repository.GetBookById(id);
            if (requestedBook != null)
            {
                string webRootpath = _environment.WebRootPath;
                string folderPath = "\\images\\";
                string fullPath = webRootpath + folderPath + requestedBook.Image;
                if (System.IO.File.Exists(fullPath))
                {
                    FileStream fileOnDisk = new FileStream(fullPath, FileMode.Open);
                    byte[] fileBytes;
                    using (BinaryReader br = new BinaryReader(fileOnDisk))
                    {
                        fileBytes = br.ReadBytes((int)fileOnDisk.Length);
                    }
                    return File(fileBytes, requestedBook.ImageMimeType);
                }
                else
                {
                    if (requestedBook.PhotoFile.Length > 0)
                    {
                        return File(requestedBook.PhotoFile, requestedBook.ImageMimeType);
                    }
                    else
                    {
                        return NotFound();
                    }
                }
            }
            else
            {
                return NotFound();
            }
        }
    }
}

YarnsMobile/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace YarnsMobile.Controllers
{
    public class MemberController : Controller
    {
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ActionName("Login")]
        public IActionResult LoginPost()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ActionName("Register")]
        public IActionResult RegisterPost()
        {
            return View();
        }
    }
}

YarnsMobile/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Yarns & Mobile - @ViewData["Title"]</title>
    <link href="~/css/reset.css" rel="stylesheet" />
    <link href="~/css/styles.css" rel="stylesheet" />
    <link href="~/css/navbar.css" rel="stylesheet" />
    <link href="~/css/footer.css" rel="stylesheet" />
    <link href="~/css/admin.css" rel="stylesheet" />
    <link href="~/css/form.css" rel="stylesheet" />
    <script src="~/js/site.js"></script>
    @RenderSection("Scripts", required: false)
</head>
<body>
    <header>
        <div class="container">
            <nav>
                <a asp-controller="Home" asp-action="Index" class="header-desktop"><img src="~/images/logo.png" alt="Yarns & Mobile" /></a>
                <div id="navicon" class="header-mobile">
                    <img src="~/images/navicon.png" alt="Navicon" />
                    <a asp-controller="Home" asp-action="Index" class="header-mobile">
                        <img src="~/images/logo-mobile.png" alt="Yarns & Mobile" />
                    </a>
                </div>

                <ul>
                    <li id="icon"><img src="~/images/xicon.png" alt="X icon" width="30" class="header-mobile" /></li>
                    <li>
                        <a href="#">Books</a>
                        <div class="divider"></div>
                        <ul>
                            <li><a asp-action="BrowseBooks" asp-controller="Books">Browse Books</a></li>
                            <li class="divider"></li>
                            <li><a asp-action="MyBooks" asp-controller="Books">My Books</a></li>
                            <li class="divider"></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">Members</a>
                        <div class="divider"></div>
                        <ul>
                            <li><a asp-controller="Member" asp-action="Login">Log In</a></li>
                            <li class="divider"></li>
                            <li><a asp-controller="Member" asp-action="Register">Register</a></li>
                            <li class="divider"></li>
                        </ul>
                    </li>
                    <li>
                        <a asp-action="Contact" asp-controller="Home">Stable Genius</a>
                        <div class="divider"></div>
                    </li>
                </ul>
                <div style="clear:both;"></div>
            </nav>
        </div>
    </header>

    <content>
        @RenderBody()
    </content>

    <footer>
        <article>
            <a asp-action="BrowseBooks" asp-controller="Books">Browse Books</a> | <a asp-controller="Member" asp-action="Login">Member Login</a> | <a asp-controller="Member" asp-action="Register">Member Register</a>
        </article>

        <article>
            &copy; 2020 Yarnes & Mobile Bookstore
        </article>
    </footer>
</body>
</html>