YarnsMobile/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using YarnsMobile.Database;
using YarnsMobile.Models;
using YarnsMobile.Repositories;
using Microsoft.EntityFrameworkCore;
using YarnsMobile.ViewModels;

namespace YarnsMobile.Controllers
{
    public class AdminController : Controller
    {
        private IRepository _repository;
        private IHostingEnvironment _environment;

        public AdminController(IRepository repository, IHostingEnvironment environment)
        {
            _repository = repository;
            _environment = environment;
        }
        public IActionResult Index()
        {
            IEnumerable<Book> books = _repository.GetBooks();
            return View(books);
        }

        [HttpGet]
        public IActionResult AddBook()
        {
            return View();
        }

        [HttpPost, ActionName("AddBook")]
        public IActionResult AddBookPost(Book book)
        {
            if(ModelState.IsValid)
            {
                if(book.CoverImage != null && book.CoverImage.Length > 0)
                {
                    book.ImageMimeType = book.CoverImage.ContentType;
                    book.Image = Path.GetFileName(book.CoverImage.FileName);
                    using (var memoryStream = new MemoryStream())
                    {
                        book.CoverImage.CopyTo(memoryStream);
                        book.PhotoFile = memoryStream.ToArray();
                    }
                }
                _repository.AddBook(book);
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }
    
        [Route("Admin/UpdateBook/{id}")]
        [HttpGet]
        public IActionResult UpdateBook(int id)
        {
            Book book = _repository.GetBookById(id);
            return View(book);
        }
        
        [Route("Admin/UpdateBook/{id}")]
        [HttpPost, ActionName("UpdateBook")]
        public IActionResult UpdateBookPost(Book book)
        {
            Book newBook = _repository.GetBookById(book.Id);
            if (ModelState.IsValid)
            {
                if (book.CoverImage != null && book.CoverImage.Length > 0)
                {
                    book.ImageMimeType = book.CoverImage.ContentType;
                    book.Image = Path.GetFileName(book.CoverImage.FileName);
                    using (var memoryStream = new MemoryStream())
                    {
                        book.CoverImage.CopyTo(memoryStream);
                        book.PhotoFile = memoryStream.ToArray();
                    }
                    newBook.Image = book.Image;
                    newBook.PhotoFile = book.PhotoFile;
                    newBook.ImageMimeType = book.ImageMimeType;
                }
                newBook.Title = book.Title;
                newBook.Author = book.Author;
                newBook.CopyrightYear = book.CopyrightYear;
                newBook.ISBN = book.ISBN;
                newBook.CurrentPrice = book.CurrentPrice;

                _repository.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        public IActionResult GetImage(int id)
        {
            Book requestedBook = _repository.GetBookById(id);
            if (requestedBook != null)
            {
                string webRootpath = _environment.WebRootPath;
                string folderPath = "\\images\\";
                string fullPath = webRootpath + folderPath + requestedBook.Image;
                if (System.IO.File.Exists(fullPath))
                {
                    FileStream fileOnDisk = new FileStream(fullPath, FileMode.Open);
                    byte[] fileBytes;
                    using (BinaryReader br = new BinaryReader(fileOnDisk))
                    {
                        fileBytes = br.ReadBytes((int)fileOnDisk.Length);
                    }
                    return File(fileBytes, requestedBook.ImageMimeType);
                }
                else
                {
                    if (requestedBook.PhotoFile.Length > 0)
                    {
                        return File(requestedBook.PhotoFile, requestedBook.ImageMimeType);
                    }
                    else
                    {
                        return NotFound();
                    }
                }
            }
            else
            {
                return NotFound();
            }
        }
    }
}

YarnsMobile/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using YarnsMobile.Models;
using YarnsMobile.Repositories;

namespace YarnsMobile.Controllers
{
    public class BooksController : Controller
    {
        private IRepository _repository;
        private IHostingEnvironment _environment;
        public BooksController(IRepository repository, IHostingEnvironment environment)
        {
            _repository = repository;
            _environment = environment;
        }
        public IActionResult BrowseBooks()
        {
            var books = _repository.GetBooks();
            return View(books);
        }

        public IActionResult MyBooks()
        {
            return View();
        }

        [Route("Books/Details/{id}")]
        public IActionResult Details()
        {
            return View();
        }

        public IActionResult GetImage(int id)
        {
            Book requestedBook = _repository.GetBookById(id);
            if (requestedBook != null)
            {
                string webRootpath = _environment.WebRootPath;
                string folderPath = "\\images\\";
                string fullPath = webRootpath + folderPath + requestedBook.Image;
                if (System.IO.File.Exists(fullPath))
                {
                    FileStream fileOnDisk = new FileStream(fullPath, FileMode.Open);
                    byte[] fileBytes;
                    using (BinaryReader br = new BinaryReader(fileOnDisk))
                    {
                        fileBytes = br.ReadBytes((int)fileOnDisk.Length);
                    }
                    return File(fileBytes, requestedBook.ImageMimeType);
                }
                else
                {
                    if (requestedBook.PhotoFile.Length > 0)
                    {
                        return File(requestedBook.PhotoFile, requestedBook.ImageMimeType);
                    }
                    else
                    {
                        return NotFound();
                    }
                }
            }
            else
            {
                return NotFound();
            }
        }
    }
}

YarnsMobile/Views/Admin/AddBook.cshtml
@model YarnsMobile.Models.Book
@{
    ViewData["Title"] = "Add Book";
}

<div class="container">
    <a asp-controller="Admin" asp-action="Index"><< Go Back</a><br /><br />

    <h2>Add a Book</h2>
    <p>
        Please fill out the information below!<br />
        All required fields are marked with (<span class="red">*</span>)
    </p>

    <form asp-action="AddBook" enctype="multipart/form-data" method="post">
        <div class="entry-group">
            <label asp-for="Title" class="requiredLabel"></label>
            <input asp-for="Title" placeholder="Title" />
            <span asp-validation-for="Title"></span>
        </div>

        <div class="entry-group">
            <label asp-for="Author" class="requiredLabel"></label>
            <input asp-for="Author" placeholder="Author" />
            <span asp-validation-for="Author"></span>
        </div>

        <div class="entry-group">
            <label asp-for="CopyrightYear" class="requiredLabel"></label>
            <input asp-for="CopyrightYear" placeholder="Copyright Year" />
            <span asp-validation-for="CopyrightYear"></span>
        </div>

        <div class="entry-group">
            <label asp-for="ISBN" class="requiredLabel"></label>
            <input asp-for="ISBN" placeholder="ISBN" />
            <span asp-validation-for="ISBN"></span>
        </div>

        <div class="entry-group">
            <label asp-for="CoverImage"></label>
            <input asp-for="CoverImage" />
            <span asp-validation-for="CoverImage"></span>
        </div>

        <div class="entry-group">
            <label asp-for="CurrentPrice" class="requiredLabel"></label>
            <input asp-for="CurrentPrice" placeholder="Current Price" />
            <span asp-validation-for="CurrentPrice"></span>
        </div>

        <input type="submit" value="Add Book" />
    </form>
</div>

YarnsMobile/Views/Admin/Index.cshtml
@model IEnumerable<YarnsMobile.Models.Book>
@{
    ViewData["Title"] = "Index";
}

<div class="container">
    <a asp-controller="Admin" asp-action="AddBook">Add new Book</a><br /><br />
    <table border="1">
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Copyright Year</th>
            <th>Current Price</th>
            <th>Update</th>
        </tr>
        @foreach(var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Title)</td>
                <td>@Html.DisplayFor(modelItem => item.Author)</td>
                <td>@Html.DisplayFor(modelItem => item.CopyrightYear)</td>
                <td>$@Html.DisplayFor(modelItem => item.CurrentPrice)</td>
                <td><a asp-action="UpdateBook" asp-controller="Admin" asp-route-id="@item.Id">Update</a></td>
            </tr>
        }
    </table>
</div>

YarnsMobile/Views/Admin/UpdateBook.cshtml
@model YarnsMobile.Models.Book
@{
    ViewData["Title"] = "Update Book";
}

<div class="container">

    <a asp-controller="Admin" asp-action="Index"><< Go Back</a><br /><br />

    @if (Model.Image != null)
    {
        <img src="@Url.Action("GetImage", "Books", new { id = Model.Id })" class="right" height="400" />
    }
    else
    {
        <img src="~/images/noimage.jpg" class="right" height="400" />
    }

    <h2>Update a Book</h2>
    <p>All required fields are marked with (<span class="red">*</span>)</p>

    <form asp-action="UpdateBook" enctype="multipart/form-data" method="post">
        <div class="entry-group">
            <label asp-for="Title" class="requiredLabel"></label>
            <input asp-for="Title" placeholder="Title" />
            <span asp-validation-for="Title"></span>
        </div>

        <div class="entry-group">
            <label asp-for="Author" class="requiredLabel"></label>
            <input asp-for="Author" placeholder="Author" />
            <span asp-validation-for="Author"></span>
        </div>

        <div class="entry-group">
            <label asp-for="CopyrightYear" class="requiredLabel"></label>
            <input asp-for="CopyrightYear" placeholder="CopyrightYear" />
            <span asp-validation-for="CopyrightYear"></span>
        </div>

        <div class="entry-group">
            <label asp-for="ISBN" class="requiredLabel"></label>
            <input asp-for="ISBN" placeholder="ISBN" />
            <span asp-validation-for="ISBN"></span>
        </div>

        <div class="entry-group">
            <label asp-for="CoverImage"></label>
            <input asp-for="CoverImage" />
            <span asp-validation-for="CoverImage"></span>
        </div>

        <div class="entry-group">
            <label asp-for="CurrentPrice" class="requiredLabel"></label>
            <input asp-for="CurrentPrice" placeholder="Current Price" />
            <span asp-validation-for="CurrentPrice"></span>
        </div>

        <input type="submit" value="Update Book" />
    </form>
</div>